-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 20:05:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema erp_modular
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `erp_modular` ;

-- -----------------------------------------------------
-- Schema erp_modular
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp_modular` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
SHOW WARNINGS;
USE `erp_modular` ;

-- -----------------------------------------------------
-- Table `customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `number_document` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `email` VARCHAR(150) NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL,
  `document_type_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `document_type_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `number_document_UNIQUE` ON `customers` (`number_document` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `customers` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `document_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `document_types` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `document_types` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `payment_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_methods` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `payment_methods` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_brands` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NULL,
  `name` VARCHAR(150) NOT NULL,
  `description` VARCHAR(255) NULL,
  `min_tock` INT NOT NULL,
  `image_url` VARCHAR(255) NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `product_categorie_id` INT NOT NULL,
  `product_brand_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_categorie_id`, `product_brand_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sale_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sale_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sale_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DECIMAL(8,2) NULL,
  `subtotal` DECIMAL(8,2) NULL,
  `product_id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `sale_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subtotal` DECIMAL(8,2) NOT NULL,
  `ivg` DECIMAL(8,2) NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `customer_id` INT NOT NULL,
  `payment_method_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  PRIMARY KEY (`id`, `customer_id`, `payment_method_id`, `series_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `series` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `series` (
  `id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `type_receipt_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_receipt_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `type_receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `type_receipts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `type_receipts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `customers`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (1, 'Carlos Perez', '72845631', '987654321', 'carlos.perez@email.com', 'Av Lima 123 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (2, 'Ana Torres', '74581236', '986541237', 'ana.torres@email.com', 'Jr Los Pinos 456 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (3, 'Luis Ramos', '71234567', '985214789', 'luis.ramos@email.com', 'Calle Las Flores 789 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (4, 'Maria Lopez', '75632148', '984123567', 'maria.lopez@email.com', 'Av Arequipa 450 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (5, 'Jose Medina', '73456789', '983214658', 'jose.medina@email.com', 'Jr Union 220 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (6, 'Lucia Rojas', '76543218', '982345671', 'lucia.rojas@email.com', 'Av Brasil 520 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (7, 'Pedro Castillo', '77894561', '981234567', 'pedro.castillo@email.com', 'Calle Sol 120 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (8, 'Rosa Salas', '74321985', '980123456', 'rosa.salas@email.com', 'Av Central 200 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (9, 'Miguel Flores', '75678912', '979234561', 'miguel.flores@email.com', 'Jr Primavera 321 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (10, 'Elena Diaz', '73412589', '978345612', 'elena.diaz@email.com', 'Calle Norte 100 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (11, 'Juan Vargas', '70987654', '977456123', 'juan.vargas@email.com', 'Av Sur 222 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (12, 'Patricia Ruiz', '72134567', '976567234', 'patricia.ruiz@email.com', 'Jr Comercio 450 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (13, 'Diego Herrera', '73245618', '975678345', 'diego.herrera@email.com', 'Calle Real 670 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (14, 'Sandra Paredes', '74125896', '974789456', 'sandra.paredes@email.com', 'Av Colonial 310 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (15, 'Ricardo Silva', '75896321', '973890567', 'ricardo.silva@email.com', 'Jr Libertad 500 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (16, 'Comercial Andina SAC', '20547896321', '972901678', 'ventas@andina.com', 'Av Industrial 100 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (17, 'Tecnologia Global SAC', '20456789123', '971012789', 'contacto@tecnoglobal.com', 'Jr Tecnologia 200 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (18, 'Distribuciones Norte SAC', '20612345789', '970123890', 'ventas@dnorte.com', 'Av Norte 150 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (19, 'Servicios Integrales SAC', '20123456789', '969234901', 'info@servicios.com', 'Calle Empresa 220 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (20, 'Importadora Pacifico SAC', '20567891234', '968345012', 'ventas@pacifico.com', 'Av Pacifico 300 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (21, 'Oficina Moderna SAC', '20432198765', '967456123', 'contacto@oficina.com', 'Jr Oficinas 410 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (22, 'Red Comercial SAC', '20678912345', '966567234', 'ventas@redcomercial.com', 'Av Comercio 510 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (23, 'Grupo Empresarial SAC', '20543219876', '965678345', 'info@grupo.com', 'Calle Central 620 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (24, 'Suministros Express SAC', '20198765432', '964789456', 'ventas@suministros.com', 'Av Logistica 730 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (25, 'Electro Peru SAC', '20654321987', '963890567', 'contacto@electroperu.com', 'Jr Energia 840 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (26, 'Carmen Vega', '71894562', '962901678', 'carmen.vega@email.com', 'Calle Olivos 120 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (27, 'Fernando Castro', '73981245', '961012789', 'fernando.castro@email.com', 'Av Universitaria 230 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (28, 'Monica Campos', '75412369', '960123890', 'monica.campos@email.com', 'Jr Amazonas 340 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (29, 'Raul Gutierrez', '74321658', '959234901', 'raul.gutierrez@email.com', 'Av Faucett 450 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (30, 'Silvia Leon', '76895412', '958345012', 'silvia.leon@email.com', 'Calle Esperanza 560 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (31, 'Constructora Lima SAC', '20598765432', '957456123', 'info@constructora.com', 'Av Obras 100 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (32, 'Alimentos del Sur SAC', '20123459876', '956567234', 'ventas@alimentos.com', 'Jr Mercado 200 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (33, 'Corporacion Orion SAC', '20678914567', '955678345', 'contacto@orion.com', 'Calle Orion 300 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (34, 'Inversiones Sol SAC', '20547891236', '954789456', 'info@sol.com', 'Av Sol 400 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (35, 'Transporte Nacional SAC', '20456987123', '953890567', 'ventas@transporte.com', 'Jr Ruta 500 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (36, 'Oscar Mendez', '73458961', '952901678', 'oscar.mendez@email.com', 'Calle Andes 600 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (37, 'Paola Reyes', '72147895', '951012789', 'paola.reyes@email.com', 'Av Libertad 700 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (38, 'Jorge Nunez', '75621489', '950123890', 'jorge.nunez@email.com', 'Jr Progreso 800 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (39, 'Daniel Ortiz', '74589632', '949234901', 'daniel.ortiz@email.com', 'Calle Surco 900 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (40, 'Veronica Soto', '73214589', '948345012', 'veronica.soto@email.com', 'Av San Martin 1000 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (41, 'Agro Export SAC', '20561234987', '947456123', 'ventas@agroexport.com', 'Av Campo 110 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (42, 'Textiles Unidos SAC', '20457896321', '946567234', 'info@textiles.com', 'Jr Algodon 220 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (43, 'Ferreteria Central SAC', '20698745123', '945678345', 'ventas@ferreteria.com', 'Calle Fierro 330 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (44, 'Import Export SAC', '20547896325', '944789456', 'contacto@importexport.com', 'Av Puerto 440 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (45, 'Innova Systems SAC', '20123654789', '943890567', 'info@innovasystems.com', 'Jr Software 550 Lima', 'RUC');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (46, 'Hector Molina', '74231568', '942901678', 'hector.molina@email.com', 'Calle Norte 660 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (47, 'Andrea Navarro', '75841236', '941012789', 'andrea.navarro@email.com', 'Av Primavera 770 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (48, 'Cesar Fuentes', '73124589', '940123890', 'cesar.fuentes@email.com', 'Jr Miraflores 880 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (49, 'Natalia Roman', '76458912', '939234901', 'natalia.roman@email.com', 'Calle Los Laureles 990 Lima', 'DNI');
INSERT INTO `customers` (`id`, `name`, `number_document`, `phone`, `email`, `address`, `document_type_id`) VALUES (50, 'Kevin Salazar', '71984562', '938345012', 'kevin.salazar@email.com', 'Av Los Heroes 111 Lima', 'DNI');

COMMIT;


-- -----------------------------------------------------
-- Data for table `document_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `document_types` (`id`, `name`) VALUES ('RUC', 'Registro Único de Contribuyentes');
INSERT INTO `document_types` (`id`, `name`) VALUES ('DNI', 'Documento Nacional de Identidad');

COMMIT;


-- -----------------------------------------------------
-- Data for table `payment_methods`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `payment_methods` (`id`, `name`) VALUES (1, 'Efectivo');
INSERT INTO `payment_methods` (`id`, `name`) VALUES (2, 'Tarjeta');
INSERT INTO `payment_methods` (`id`, `name`) VALUES (3, 'Transferencia');
INSERT INTO `payment_methods` (`id`, `name`) VALUES (4, 'Yape');
INSERT INTO `payment_methods` (`id`, `name`) VALUES (5, 'Plin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `product_brands`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (1, 'Lenovo', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (2, 'Epson', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (3, 'Office pro', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (4, 'LG', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (5, 'Redragon', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (6, 'Logitech', NULL);
INSERT INTO `product_brands` (`id`, `name`, `description`) VALUES (7, 'Sony', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `product_categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `product_categories` (`id`, `name`, `description`) VALUES (1, 'Tecnologia', NULL);
INSERT INTO `product_categories` (`id`, `name`, `description`) VALUES (2, 'Oficina', NULL);
INSERT INTO `product_categories` (`id`, `name`, `description`) VALUES (3, 'Mobiliario', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `products`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (1, 'P001', 'Laptop Lenovo ThinkPad E14', 'NULL', 10, 'NULL', 100, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (2, 'P002', 'Laptop Lenovo IdeaPad 5', 'NULL', 8, 'NULL', 95, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (3, 'P003', 'Monitor LG 24 pulgadas', 'NULL', 15, 'NULL', 60, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (4, 'P004', 'Monitor LG UltraWide 29', 'NULL', 8, 'NULL', 120, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (5, 'P005', 'Teclado Redragon Kumara K552', 'NULL', 25, 'NULL', 30, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (6, 'P006', 'Mouse Logitech G203', 'NULL', 30, 'NULL', 20, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (7, 'P007', 'Mouse Logitech MX Master 3S', 'NULL', 12, 'NULL', 80, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (8, 'P008', 'Audifonos Sony WH-CH520', 'NULL', 15, 'NULL', 55, 1, 7);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (9, 'P009', 'Parlante Sony SRS-XB100', 'NULL', 10, 'NULL', 45, 1, 7);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (10, 'P010', 'Laptop Lenovo LOQ Gaming', 'NULL', 6, 'NULL', 180, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (11, 'P011', 'Impresora Epson EcoTank L3250', 'NULL', 8, 'NULL', 150, 2, 2);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (12, 'P012', 'Impresora Epson L4260', 'NULL', 6, 'NULL', 180, 2, 2);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (13, 'P013', 'Escaner Epson WorkForce ES-50', 'NULL', 10, 'NULL', 110, 2, 2);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (14, 'P014', 'Silla Ejecutiva Office Pro Negra', 'NULL', 15, 'NULL', 130, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (15, 'P015', 'Escritorio Office Pro 120cm', 'NULL', 10, 'NULL', 140, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (16, 'P016', 'Archivador Metalico Office Pro', 'NULL', 12, 'NULL', 90, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (17, 'P017', 'Mesa de Reuniones Office Pro', 'NULL', 5, 'NULL', 220, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (18, 'P018', 'Silla Ergonomica Office Pro', 'NULL', 8, 'NULL', 180, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (19, 'P019', 'Teclado Logitech K380', 'NULL', 25, 'NULL', 35, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (20, 'P020', 'Mouse Logitech M185', 'NULL', 40, 'NULL', 15, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (21, 'P021', 'Webcam Logitech C920', 'NULL', 12, 'NULL', 75, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (22, 'P022', 'Auriculares Redragon Zeus X', 'NULL', 10, 'NULL', 65, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (23, 'P023', 'Mouse Redragon Cobra', 'NULL', 20, 'NULL', 28, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (24, 'P024', 'Teclado Redragon Fizz', 'NULL', 18, 'NULL', 40, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (25, 'P025', 'Monitor LG 27 pulgadas IPS', 'NULL', 8, 'NULL', 135, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (26, 'P026', 'Televisor LG 43 Smart TV', 'NULL', 5, 'NULL', 320, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (27, 'P027', 'Barra de Sonido LG', 'NULL', 7, 'NULL', 180, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (28, 'P028', 'Audifonos Sony MDR-ZX110', 'NULL', 25, 'NULL', 18, 1, 7);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (29, 'P029', 'Camara Sony ZV-E10', 'NULL', 4, 'NULL', 550, 1, 7);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (30, 'P030', 'Laptop Lenovo Yoga Slim 7', 'NULL', 5, 'NULL', 220, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (31, 'P031', 'Resma Papel A4 Office Pro', 'NULL', 100, 'NULL', 6, 2, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (32, 'P032', 'Perforadora Office Pro', 'NULL', 30, 'NULL', 12, 2, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (33, 'P033', 'Engrapadora Office Pro', 'NULL', 40, 'NULL', 8, 2, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (34, 'P034', 'Pizarra Blanca Office Pro', 'NULL', 8, 'NULL', 70, 2, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (35, 'P035', 'Silla de Visita Office Pro', 'NULL', 20, 'NULL', 75, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (36, 'P036', 'Escritorio Ejecutivo Office Pro', 'NULL', 6, 'NULL', 260, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (37, 'P037', 'Impresora Epson EcoTank L6270', 'NULL', 4, 'NULL', 240, 2, 2);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (38, 'P038', 'Proyector Epson PowerLite', 'NULL', 3, 'NULL', 480, 2, 2);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (39, 'P039', 'Router Lenovo Smart Hub', 'NULL', 8, 'NULL', 90, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (40, 'P040', 'Dock Lenovo USB-C', 'NULL', 15, 'NULL', 70, 1, 1);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (41, 'P041', 'Mouse Pad Redragon XL', 'NULL', 35, 'NULL', 18, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (42, 'P042', 'Microfono Redragon Blazar', 'NULL', 10, 'NULL', 55, 1, 5);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (43, 'P043', 'Bocinas Logitech Z213', 'NULL', 12, 'NULL', 45, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (44, 'P044', 'Combo Teclado y Mouse Logitech MK270', 'NULL', 20, 'NULL', 38, 1, 6);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (45, 'P045', 'Audifonos Sony In-Ear', 'NULL', 30, 'NULL', 25, 1, 7);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (46, 'P046', 'Soporte para Monitor LG', 'NULL', 10, 'NULL', 48, 1, 4);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (47, 'P047', 'Librero Office Pro 5 Niveles', 'NULL', 8, 'NULL', 170, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (48, 'P048', 'Gabinete Archivador Office Pro', 'NULL', 6, 'NULL', 145, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (49, 'P049', 'Escritorio Compacto Office Pro', 'NULL', 10, 'NULL', 115, 3, 3);
INSERT INTO `products` (`id`, `code`, `name`, `description`, `min_tock`, `image_url`, `price`, `product_categorie_id`, `product_brand_id`) VALUES (50, 'P050', 'Impresora Epson EcoTank M2170', 'NULL', 5, 'NULL', 280, 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `series`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (1, 'F001', 1);
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (2, 'F002', 1);
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (3, 'B001', 2);
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (4, 'B002', 2);
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (5, 'NV001', 3);
INSERT INTO `series` (`id`, `number`, `type_receipt_id`) VALUES (6, 'NV002', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `type_receipts`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp_modular`;
INSERT INTO `type_receipts` (`id`, `name`) VALUES (1, 'Factura');
INSERT INTO `type_receipts` (`id`, `name`) VALUES (2, 'Boleta');
INSERT INTO `type_receipts` (`id`, `name`) VALUES (3, 'Nota de venta');

COMMIT;

