worker_processes  1;

events {
    worker_connections  1024;
}

http {
      include /etc/nginx/mime.types;

    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/x-javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;
    server {
             listen 80 default_server;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        # ============================================================
        # Native Federation
        # ============================================================

        location = /remoteEntry.json {
            try_files $uri =404;

            default_type application/json;

            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }

        # ============================================================
        # Archivos estáticos
        # ============================================================

        location ~* \.(js|mjs|css|json|map|woff|woff2|ttf|eot|svg|png|jpg|jpeg|gif|ico|webp)$ {
            try_files $uri =404;

            add_header Cache-Control "public, max-age=31536000, immutable";
        }
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
